### ISSUE TITLE
Problema ao extrair zip da base

### ISSUE THREAD

**Issue by jpconfessor** [EvoluxBR/open-cnl#8]
Um erro é gerado ao extrair o arquivo ZIP da base da anatel

```
 try:
    arquivo_txt = self.extrair_base_do_arquivo_zip(arquivo_zip)
except Exception:
    raise ErroAoExtrairBaseDaANATEL
```

**Comment by victor-torres** [comment]
O problema é causado pela ANATEL, o download da Central CNL não está funcionando até mesmo pelo site oficial da agência. Tanto o request pelo Python quanto o feito pelo site retorna a seguinte mensagem:

```
   POST http://sistemas.anatel.gov.br/areaarea/N_Download/Tela.asp
        ← 302 text/html 184B 45.7s
   GET http://sistemas.anatel.gov.br/AREAAREA/DownLoad/CE_F_113216.ZIP
       ← 200 text/html 188B 840ms
```

> The requested URL was rejected. Please consult with your administrator.
> 
> Your support ID is: 5460556138154383368

**Comment by victor-torres** [comment]
Agora parece que a ANATEL está rejeitando a maneira como fazemos a requisição da base de dados em formato ZIP. Precisamos corrigir e lançar uma nova versão.

**Comment by victor-torres** [comment]
Foi lançada uma versão há 6 dias. Caso esteja tudo OK irei fechar este ticket hoje.
